### PR TITLE
Make XDL to XBF changes in source code

### PR DESCRIPTION
**Pull request by ahuston-0**
Will be merged into main via #25.

### CODE REVIEW

**Comment by ahuston-0** [comment]
Looks like the changes went through without making Github freak out trying to display the diff... Looks like the only references to XDL left are in the `nancy` folder. Thinking I leave that alone so it doesn't cause issues down the line?

**Comment by ahuston-0** [comment]
For some reason I'm running nightly right now, so I ran the below and it looks like its working. Feel free to checkout the branch and confirm.

`cargo clean; cargo build; cargo clean; cargo test; cargo clean; cargo tarpaulin; cargo clean; cargo miri setup; cargo miri test`

Only one that I omitted was `cargo audit` because for some reason it was locking up on my system. Think it was an issue trying to clone the advisory-db and not anything to do with this PR.

**Review by TheMadMaker2 — APPROVED** [review]
I think its good

**Review by dkrautha — CHANGES_REQUESTED** [review]
So I've been meaning to for a while, but can we just remove the Xdl / Xbf prefix from the types? When importing them they'll have to be namespaced by a module including the xdl / xbf prefix, so having it on the types themselves is kinda redundant.

**Comment by ahuston-0** [comment]
> So I've been meaning to for a while, but can we just remove the Xdl / Xbf prefix from the types? When importing them they'll have to be namespaced by a module including the xdl / xbf prefix, so having it on the types themselves is kinda redundant.

As discussed, renaming XbfVec to Vec clashes with the standard Rust namespace. The four commits that were pushed to drop the Xbf prefix have been reverted.

**Comment by ahuston-0** [comment]
@dkrautha pls approve and I'll merge

**Review by dkrautha — APPROVED** [review]
As we can see I have smol brain, looks good.

**Pull request merged**
