### PR TITLE
Add nightly checks (including Miri)

### PR DESCRIPTION
**Pull request by ahuston-0**

### CODE REVIEW

**Comment by ahuston-0** [comment]
Adds Miri and nightly checks that continue on error and do not fail fast (ie. if release build fails on Linux it will try to test it anyway, and if Miri fails on Mac then Windows won't stop running, etc). Also hopefully added manual workflow runs but we won't know for sure on that one until its merged.

**Comment by ahuston-0** [comment]
I'll run these steps manually for #16 and #18, but I figured this prevents me from needing to run Miri every time we introduce a feature with new memory semantics. Also, it should hopefully not block merging if the latest nightly release did not include a Miri component (as they sometimes do).

**Comment by ahuston-0** [comment]
huh github is being annoying and erasing my checks now that I removed the dud file.... Please check [this github actions run](https://github.com/dkrautha/GrailNetworking/actions/runs/5307576481) as evidence.

**Comment by ahuston-0** [comment]
And with [this github actions run](https://github.com/dkrautha/GrailNetworking/actions/runs/5307627777/jobs/9606326212) I've removed caching for the nightly checks to get rid of the weird errors we were getting.

**Comment by ahuston-0** [comment]
Overall, this should add an optional, yet still present method of future-proofing the current code and validating the memory model.

**Review by dkrautha — APPROVED** [review]
Looks great lets send it!

**Pull request merged**
